version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - echo Running post_build commands
      - mkdir artifact
      - zip -qr build-output.zip *
      - cp build-output.zip artifact
      - echo Build completed on `date`
artifacts:
  files:
    - artifact/build-output.zip